### ISSUE TITLE
Adds "track_errors = On" which is deprecated with PHP 7.2

### ISSUE THREAD

**Issue by mbiebl** [RonaldCarter/PHPManager#12]
Hi,

we are using PHP 7.2.7 with IIS/Windows Server 2016.

When using PHP Manager to switch PHP from debug into development mode, it adds the following line to php.ini:
```
track_errors = On
```
With php 7.2 this now generates a deprecation warning:
```
Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
```
See also http://php.net/manual/en/migration72.deprecated.php

PHP Manager should stop adding/setting track_errors when PHP 7.2 or newer is used.

**Comment by RonaldCarter** [comment]
Potentially resolved testing in new branch

**Comment by mbiebl** [comment]
I've tested the Installer from https://github.com/RonaldCarter/PHPManager/blob/9b6411cf633920b795f8aeaeb8f0ae1d6c171d80/bin/Release/PHPManagerForIIS.msi and it fixes the issue for me

**Comment by RonaldCarter** [comment]
I am glad it has been fixed, well merge into master later in the week
