### ISSUE TITLE
Proposal on taking over PHPManager as an organization

### ISSUE THREAD

**Issue by lextm** [RonaldCarter/PHPManager#13]
I wrote a proposal at https://github.com/phpmanager/phpmanager/issues/1

If you like to join, let me know.

**Comment by RonaldCarter** [comment]
I am happy to support this initiative, I would love to get some proper programmers on this as all I have done is from google searches

**Comment by lextm** [comment]
@RonaldCarter I have sent you an invitation to join the Maintainers team. We might discuss later on what exactly can go to the 2.0 release, and then work on the remaining items.

**Comment by mbiebl** [comment]
@RonaldCarter now that @lextm has made the v2.0 release, I wonder whether this github repo should be archived or at least mention in the README.md that the successor can be found at https://github.com/phpmanager/phpmanager to avoid confusion by users finding the github repo looking for phpmanager.

**Comment by lextm** [comment]
@mbiebl There are differences in the two forks (this one and mine), so right now it is hard to say terms like "successor". For instance, this fork tends to use .NET 4.x and mainly focuses on IIS 10, and the way it handles PHP obsolete features is different from my fork. People have their choices, and that's not a bad thing.

**Comment by mbiebl** [comment]
Apologies, this was a misunderstanding on my part. I thought that the phpmanager/phpmanager project would try to consolidate the efforts and there would only be one "version" of phpmanager going forward.
