### ISSUE TITLE
PHPMGRSNF.SNK.pfx is password protected and prevents build

### ISSUE THREAD

**Issue by Knagis** [RonaldCarter/PHPManager#5]
`PHPMGRSNF.SNK.pfx` file is password protected and as such the project cannot be built.

The project files actually include post-build step that sets up delay-signing for the compiled files (in debug mode) but that seems to be made for the old version and no longer works.

However I would vote for the password simply be removed and the snk file being checked in GIT to simplify collaboration.

**Comment by RonaldCarter** [comment]
Yeah the delayed signing and the debug build are leftovers from my conversion.

I needed a signed file to use to make it work, I will do some reading about distribution of the key file.
I agree with your changes and will hopefully get this done soon

**Comment by RonaldCarter** [comment]
I have added your pull request thank you for that. I am working on the Strong Name issues now

**Comment by RonaldCarter** [comment]
Removed the passworf from the SNK
