### ISSUE TITLE
Use Microsoft.Web.Administration 10 instead of 7

### ISSUE THREAD

**Issue by RonaldCarter** [RonaldCarter/PHPManager#8]

**Comment by RonaldCarter** [comment]
This will be an ongoing issue due to incompatibility between Microsoft.Web.Administration.10.0.0 and Microsoft.Web.Management.7.0.0.0

Waiting for Microsoft.Web.Management.10.0.0.0 release

**Comment by Buliwyfa** [comment]
Thanks a lot test it on Windows 2016 too  and it works.

THANKS A LOT!!
